// <auto-generated />
namespace Sistema.Ifsp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class criandodatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criandodatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "201511102328412_criando-database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
