// <auto-generated />
namespace Sistema.Ifsp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class excluindoatributonomedaclassevaga : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(excluindoatributonomedaclassevaga));
        
        string IMigrationMetadata.Id
        {
            get { return "201510032355553_excluindo-atributo-nome-da-classe-vaga"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
