// <auto-generated />
namespace Sistema.Acesso.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removendo_pk_de_classe_herdadas_de_pessoaFisica : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removendo_pk_de_classe_herdadas_de_pessoaFisica));
        
        string IMigrationMetadata.Id
        {
            get { return "201508112059328_Removendo_pk_de_classe_herdadas_de_pessoaFisica"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
